services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8091:8091
    depends_on:
      - postgres
#      postgres:
#        condition: service_healthy
#    networks:
#      - springboot-postgres-network
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgres
#    networks:
#      - springboot-postgres-network
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready", "-d", "mydatabase" ]
#      interval: 30s
#      timeout: 30s
#      retries: 5
#      start_period: 20s
volumes:
  postgres-data:
#networks:
#  springboot-postgres-network:
#    name: springboot-postgres-network
